[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirect for root to intro page
[[redirects]]
  from = "/"
  to = "/intro"
  status = 302
